# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171104_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='property',
            new_name='complex',
        ),
    ]
