# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('legal', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processed', 'Processed'), ('charged', 'Charged'), ('cancelled', 'Cancelled'), ('waived', 'Waived'), ('paid_in_full', 'Paid In Full'), ('paid_in_part', 'Paid In Part')], max_length=12)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_processed', models.DateField(blank=True, null=True)),
                ('date_charged', models.DateField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('paid_in_full_on', models.DateField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legal.Lease')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('card', 'Credit/debit'), ('ach', 'ACH (Bank transfer)')], max_length=13)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('cancelled', 'Cancelled'), ('denied', 'Denied')], max_length=9)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.Invoice')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='billing.Invoice'),
        ),
    ]
