# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_due', models.DateField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legal.Lease')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('card', 'Credit/debit'), ('ach', 'ACH (Bank transfer)')], max_length=13)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('denied', 'Denied')], max_length=9)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legal.Lease')),
                ('paid_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='billing.Payment'),
        ),
    ]
