# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_status',
            new_name='status',
        ),
    ]
