# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20171104_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='created_on',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='charge',
            name='charge_status',
            field=models.CharField(choices=[('created', 'Created'), ('processed', 'Processed'), ('charged', 'Charged'), ('cancelled', 'Cancelled'), ('paid_in_full', 'Paid In Full'), ('paid_in_part', 'Paid In Part')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='date_charged',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='date_processed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='paid_in_full_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
