# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.Unit')),
            ],
        ),
    ]
