# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.Unit'),
            preserve_default=False,
        ),
    ]
