# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='occupants',
            field=models.ManyToManyField(related_name='occupants_set', to='authentication.Tenant'),
        ),
    ]
