# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(editable=False),
        ),
    ]
