# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='lessor',
            new_name='property',
        ),
    ]
