# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_auto_20171021_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='property',
            new_name='property_owner',
        ),
    ]
