# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_auto_20170825_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='period',
            field=models.DurationField(help_text='Use the following format: D HH:MM:SS'),
        ),
    ]
