# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_lease_occupants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='leasees',
            field=models.ManyToManyField(related_name='tenant_leasees_set', to='authentication.Tenant'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='occupants',
            field=models.ManyToManyField(related_name='tenant_occupants_set', to='authentication.Tenant'),
        ),
    ]
