# Generated by Django 2.0.2 on 2018-03-03 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_auto_20180302_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_estate.Unit'),
        ),
    ]
