# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_auto_20170909_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='tenant_occupants_set', to='authentication.Tenant'),
        ),
    ]
