# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_auto_20170825_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='period',
            new_name='length',
        ),
    ]
