# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_unit_tenants'),
        ('authentication', '0001_initial'),
        ('legal', '0004_auto_20170923_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='leasees',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='leasors',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='occupants',
        ),
        migrations.AddField(
            model_name='lease',
            name='lessor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lease',
            name='tenants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.Tenant'),
            preserve_default=False,
        ),
    ]
