# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_auto_20170924_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='length',
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(),
        ),
    ]
