# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_auto_20170825_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='name',
            field=models.CharField(default='6 Months', max_length=100),
            preserve_default=False,
        ),
    ]
