# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0006_term_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='term',
        ),
        migrations.AddField(
            model_name='lease',
            name='length',
            field=models.DurationField(default='30 00:00:00', help_text='Use the following format: D HH:MM:SS', unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
