# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0006_auto_20170925_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenants',
        ),
    ]
