# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('properties', '0003_auto_20170811_0103'),
        ('legal', '0007_auto_20170825_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='leasees',
            field=models.ManyToManyField(to='tenants.Tenant'),
        ),
        migrations.AddField(
            model_name='lease',
            name='leasors',
            field=models.ManyToManyField(to='properties.Property'),
        ),
    ]
