# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import property_management.validators.phone_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11, validators=[property_management.validators.phone_number.validate_phone_number])),
                ('ssn', models.CharField(max_length=11)),
            ],
        ),
    ]
