# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20170802_2353'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='occupant_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('occupant', 'Occupant')], default='primar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Unit'),
        ),
    ]
