# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import property_management.validators.phone_number


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20170819_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[property_management.validators.phone_number.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
