# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20170819_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='occupant_type',
            field=models.CharField(choices=[(1, 'Primary'), (2, 'Occupant')], max_length=100),
        ),
    ]
