# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_auto_20170819_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='occupant_type',
            field=models.IntegerField(choices=[(1, 'Primary'), (2, 'Occupant')]),
        ),
    ]
