# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_auto_20170819_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='occupant_type',
            field=models.IntegerField(),
        ),
    ]
