# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_auto_20170819_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupantType',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('occupant_type_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='tenant',
            name='occupant_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.OccupantType'),
        ),
    ]
