# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
