# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import property_management.validators.phone_number


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='8018609605', max_length=11, validators=[property_management.validators.phone_number.validate_phone_number]),
            preserve_default=False,
        ),
    ]
