# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='10464 South Jordan Gateway', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='South Jordan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.CharField(default='Aaron Chesley', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default='Utah', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.IntegerField(default=84095),
            preserve_default=False,
        ),
    ]
