# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20170802_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
