# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('unit_number', models.IntegerField(default=None)),
                ('sq_ft', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('allow_dogs', models.BooleanField(default=False)),
                ('allow_cats', models.BooleanField(default=False)),
                ('allow_smoking', models.BooleanField(default=False)),
            ],
        ),
    ]
