# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_tenant_unit'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='tenants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Tenant'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Tenant'),
        ),
        migrations.AddField(
            model_name='unit',
            name='tenants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Tenant'),
        ),
    ]
