# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='client',
        ),
    ]
