# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20170802_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
