# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20170802_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='allow_cats',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='allow_dogs',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='allow_smoking',
        ),
    ]
