# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
