# Generated by Django 3.0.3 on 2020-06-27 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('communication', '0002_auto_20200620_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
