# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_maintenancerequest_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='photo',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
