# Generated by Django 3.0.3 on 2020-09-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_maintenancerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
