# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import property_management.validators.phone_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallableUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccupantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupant_type_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericUser',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.CallableUser')),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.callableuser',),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.CallableUser')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[property_management.validators.phone_number.validate_phone_number])),
                ('ssn', models.CharField(blank=True, max_length=11, null=True)),
                ('occupant_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.OccupantType')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Unit')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.callableuser',),
        ),
    ]
