# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_tenant_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_type',
        ),
        migrations.DeleteModel(
            name='TenantType',
        ),
    ]
