# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_genericuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='genericuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
