# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_tenant_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OccupantType',
            new_name='TenantType',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='occupant_type',
            new_name='tenant_type',
        ),
        migrations.RenameField(
            model_name='tenanttype',
            old_name='occupant_type_id',
            new_name='tenant_type_id',
        ),
    ]
