# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170826_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenanttype',
            old_name='tenant_type_id',
            new_name='numerical_order',
        ),
    ]
