# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170827_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
