# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170826_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='callableuser_ptr',
        ),
        migrations.AddField(
            model_name='tenant',
            name='genericuser_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
