# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_genericuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callableuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
