# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170828_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callableuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
