# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20170828_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callableuser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
