# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20170827_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
