# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20170827_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='genericuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='genericuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='genericuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
