# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20170829_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callableuser',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True),
        ),
    ]
