# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20170829_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callableuser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
